
a = input('Enter the first number: ')
b = input('Enter the second number: ')
a = int(a)
b = int(b)
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a * b}")
print(f"{a} / {b} = {a / b}")
print(f"{a} % {b} = {a % b}")
print(f"{a} ** {b} = {a ** b}")
print(f"{a} // {b} = {a // b}")